version: "3"
   
services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/python/app
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  consumer:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/home/python/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"